module rom_4kx8(
    input clk,
    input [11:0] addr,
    output reg [7:0] data
    );

reg [7:0] rom [4095:0];  // 4kx8 read only RAM

// Memory file is generated by
// hexdump -e '16/1 "%02x " "\n"' rom_data.bin >> rom_data.mem

initial
    $readmemh("rom_data.mem", rom);

always @ (posedge clk)
    data <= rom[addr];


endmodule