set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

#Switches
set_property PACKAGE_PIN V17 [get_ports {A[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {B[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN V15 [get_ports {B[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN W14 [get_ports {B[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN W13 [get_ports {B[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN V2 [get_ports {C[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
set_property PACKAGE_PIN T3 [get_ports {C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
set_property PACKAGE_PIN T2 [get_ports {C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
set_property PACKAGE_PIN R3 [get_ports {C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[3]}]
set_property PACKAGE_PIN W2 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property PACKAGE_PIN U1 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property PACKAGE_PIN T1 [get_ports {D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
set_property PACKAGE_PIN R2 [get_ports {D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {SEG_TOP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[6]}]
set_property PACKAGE_PIN W6 [get_ports {SEG_TOP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[5]}]
set_property PACKAGE_PIN U8 [get_ports {SEG_TOP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[4]}]
set_property PACKAGE_PIN V8 [get_ports {SEG_TOP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEG_TOP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[2]}]
set_property PACKAGE_PIN V5 [get_ports {SEG_TOP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[1]}]
set_property PACKAGE_PIN U7 [get_ports {SEG_TOP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG_TOP[0]}]

set_property PACKAGE_PIN U2 [get_ports {ANODE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[0]}]
set_property PACKAGE_PIN U4 [get_ports {ANODE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[1]}]
set_property PACKAGE_PIN V4 [get_ports {ANODE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[2]}]
set_property PACKAGE_PIN W4 [get_ports {ANODE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ANODE[3]}]
